"""Exercise the installed monitor on an isolated bus via dbus-run-session."""

import asyncio
import os
from pathlib import Path
from tempfile import TemporaryDirectory

from dbus_event_log.config import Config, DBusConfig, MQTTConfig, StorageConfig, set_config
from dbus_event_log.models import DBusEvent, EventType
from dbus_event_log.monitor import DBusMonitor
from dbus_event_log.storage import SQLiteStorage


async def smoke_monitor(database: Path) -> None:
    """Require a real bus signal to reach both SQLite and the event observer."""
    if not os.environ.get("DBUS_SESSION_BUS_ADDRESS"):
        raise RuntimeError("Run this smoke check under dbus-run-session")
    service = "com.victronenergy.smoke.monitor"
    set_config(
        Config(
            dbus=DBusConfig(bus_type="session", services=["com.victronenergy.smoke.*"]),
            mqtt=MQTTConfig(enabled=False),
            storage=StorageConfig(sqlite_path=database),
        )
    )
    observed = asyncio.Event()

    async def observe(event: DBusEvent) -> None:
        """Record only the service acquisition generated by this check."""
        if event.service_name == service and event.event_type == EventType.SERVICE_ADDED:
            observed.set()

    monitor = DBusMonitor(event_handler=observe)
    acquired = False
    try:
        await monitor.start()
        result = monitor.bus.dbus.RequestName(service, 0)
        if result != 1:
            raise AssertionError(f"Expected primary name ownership, received {result}")
        acquired = True
        await asyncio.wait_for(observed.wait(), timeout=10)
        # Reopen the actual database to verify committed persistence independently.
        stored = SQLiteStorage(StorageConfig(sqlite_path=database)).query(
            service=service, event_type=EventType.SERVICE_ADDED
        )
        if len(stored) != 1 or stored[0]["member"] != "NameOwnerChanged":
            raise AssertionError(f"Expected one persisted service acquisition, received {stored}")
    finally:
        try:
            if acquired:
                monitor.bus.dbus.ReleaseName(service)
        finally:
            await asyncio.wait_for(monitor.stop(), timeout=10)


if __name__ == "__main__":
    with TemporaryDirectory(prefix="dbus-event-log-smoke-") as temporary_directory:
        asyncio.run(smoke_monitor(Path(temporary_directory) / "events.db"))
