"""Exercise the installed monitor on an isolated bus via dbus-run-session."""

import asyncio
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from selectors import EVENT_READ, DefaultSelector
from tempfile import TemporaryDirectory
from typing import Any

# This smoke entry point runs inside the native image with the optional Gio runtime.
# pylint: disable-next=import-error
from gi.repository import Gio, GLib

from dbus_event_log.config import Config, DBusConfig, MQTTConfig, StorageConfig, set_config
from dbus_event_log.models import DBusEvent, EventType
from dbus_event_log.monitor import DBusMonitor
from dbus_event_log.storage import SQLiteStorage


def register_test_service(connection: Any) -> int:
    """Expose a synthetic setter and error without any hardware access."""
    interface = Gio.DBusNodeInfo.new_for_xml("""
      <node><interface name="com.victronenergy.BusItem">
        <method name="SetValue"><arg type="v" direction="in"/>
          <arg type="i" direction="out"/></method>
        <method name="Fail"/>
      </interface></node>
    """).interfaces[0]

    def handle(
        _connection: Any,
        _sender: str,
        _path: str,
        _interface: str,
        member: str,
        parameters: Any,
        invocation: Any,
    ) -> None:
        if member == "Fail":
            invocation.return_dbus_error("org.example.Refused", "Synthetic refusal")
            return
        value = parameters.unpack()[0]
        connection.emit_signal(
            None,
            "/",
            "com.victronenergy.BusItem",
            "ItemsChanged",
            GLib.Variant(
                "(a{sa{sv}})",
                (
                    {
                        "/Settings/Limit": {
                            "Value": GLib.Variant("i", value),
                            "Text": GLib.Variant("s", str(value)),
                        }
                    },
                ),
            ),
        )
        invocation.return_value(GLib.Variant("(i)", (0,)))

    return int(connection.register_object("/Settings/Limit", interface, handle, None, None))


def verify_capture(events: list[DBusEvent], caller_name: str, database: Path) -> None:
    """Check attribution, reply correlation and committed signal/error records."""
    calls = [event for event in events if event.event_type == EventType.METHOD_CALL]
    assert len(calls) == 3, events
    assert all(event.source_unique_name == caller_name for event in calls)
    assert all(event.kwargs["caller"]["process_id"] == os.getpid() for event in calls)
    assert all(event.kwargs["caller"]["unix_user_id"] == os.getuid() for event in calls)
    replies = [
        event for event in events if event.event_type in (EventType.METHOD_RETURN, EventType.ERROR)
    ]
    assert {e.kwargs["call_event_id"] for e in replies} == {str(e.id) for e in calls}
    assert len([e for e in events if e.member == "ItemsChanged"]) == 2
    saved = SQLiteStorage(StorageConfig(sqlite_path=database)).query(event_type=EventType.ERROR)
    assert saved[0]["error_name"] == "org.example.Refused"
    assert json.loads(saved[0]["kwargs"])["caller"]["process_id"] == os.getpid()


async def smoke_monitor(database: Path) -> None:
    """Capture real Victron signals, attributed writes, success and failure on a private bus."""
    if not os.environ.get("DBUS_SESSION_BUS_ADDRESS"):
        raise RuntimeError("Run this smoke check under dbus-run-session")
    service = "com.victronenergy.smoke.monitor"
    set_config(
        Config(
            dbus=DBusConfig(
                bus_type="session", services=["com.victronenergy.smoke.*"], capture_methods=True
            ),
            mqtt=MQTTConfig(enabled=False),
            storage=StorageConfig(sqlite_path=database),
        )
    )
    observed = asyncio.Event()
    events: list[DBusEvent] = []

    async def observe(event: DBusEvent) -> None:
        """Record only the service acquisition generated by this check."""
        events.append(event)
        if event.service_name == service and event.event_type == EventType.SERVICE_ADDED:
            observed.set()

    monitor = DBusMonitor(event_handler=observe)
    acquired = False
    caller = None
    registration = None
    try:
        await monitor.start()
        result = monitor.bus.dbus.RequestName(service, 0)
        if result != 1:
            raise AssertionError(f"Expected primary name ownership, received {result}")
        acquired = True
        await asyncio.wait_for(observed.wait(), timeout=10)
        # Reopen the actual database to verify committed persistence independently.
        stored = SQLiteStorage(StorageConfig(sqlite_path=database)).query(
            service=service, event_type=EventType.SERVICE_ADDED
        )
        if len(stored) != 1 or stored[0]["member"] != "NameOwnerChanged":
            raise AssertionError(f"Expected one persisted service acquisition, received {stored}")
        registration = register_test_service(monitor.bus.con)
        caller = Gio.DBusConnection.new_for_address_sync(
            os.environ["DBUS_SESSION_BUS_ADDRESS"],
            Gio.DBusConnectionFlags.AUTHENTICATION_CLIENT
            | Gio.DBusConnectionFlags.MESSAGE_BUS_CONNECTION,
            None,
            None,
        )
        caller.set_exit_on_close(False)

        async def invoke(destination: str, method: str, parameters: Any = None) -> Any:
            return await asyncio.to_thread(
                caller.call_sync,
                destination,
                "/Settings/Limit",
                "com.victronenergy.BusItem",
                method,
                parameters,
                None,
                Gio.DBusCallFlags.NONE,
                5000,
                None,
            )

        # Exercise both destination addressing modes used by real clients.
        for destination in (service, monitor.bus.con.get_unique_name()):
            result = await invoke(
                destination, "SetValue", GLib.Variant("(v)", (GLib.Variant("i", 12),))
            )
            assert result.unpack() == (0,)
        try:
            await invoke(service, "Fail")
        except GLib.Error:
            pass
        else:
            raise AssertionError("The synthetic error was not delivered to the original caller")
        async with asyncio.timeout(10):
            while (
                len(
                    [
                        e
                        for e in events
                        if e.event_type in (EventType.METHOD_RETURN, EventType.ERROR)
                    ]
                )
                < 3
            ):
                monitor.raise_if_failed()
                await asyncio.sleep(0.02)
        verify_capture(events, caller.get_unique_name(), database)
    finally:
        try:
            if acquired:
                monitor.bus.dbus.ReleaseName(service)
            if registration is not None:
                monitor.bus.con.unregister_object(registration)
            if caller is not None:
                caller.close_sync(None)
        finally:
            await asyncio.wait_for(monitor.stop(), timeout=10)
            monitor.raise_if_failed()


def smoke_cli_stop(directory: Path) -> None:
    """SIGTERM and the default CLI coordinator must exit cleanly without a supervisor restart."""
    environment = dict(
        os.environ,
        DBUS_EVENT_LOG_DBUS_BUS_TYPE="session",
        DBUS_EVENT_LOG_STORAGE_SQLITE_PATH=str(directory / "cli.db"),
        DBUS_EVENT_LOG_MQTT_ENABLED="false",
    )
    with subprocess.Popen(
        [
            sys.executable,
            "-m",
            "dbus_event_log.cli",
            "monitor",
            "--duration",
            "15",
            "--capture-methods",
        ],
        env=environment,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    ) as process:
        assert process.stdout is not None
        try:
            deadline = time.monotonic() + 10
            startup_output = bytearray()
            with DefaultSelector() as selector:
                selector.register(process.stdout, EVENT_READ)
                while time.monotonic() < deadline:
                    if selector.select(timeout=0.1):
                        line = os.read(process.stdout.fileno(), 8192)
                        startup_output.extend(line)
                        if b"Temporary capture:" in startup_output:
                            break
                        if not line:
                            raise AssertionError(startup_output.decode())
                else:
                    raise AssertionError("CLI failed to start within 10 seconds")
            process.terminate()
            output, _ = process.communicate(timeout=10)
            assert process.returncode == 0, output.decode()
        finally:
            if process.poll() is None:
                process.kill()
                process.wait()
    result = subprocess.run(
        [sys.executable, "-m", "dbus_event_log.cli", "monitor", "--duration", "1"],
        env=environment,
        capture_output=True,
        timeout=10,
        check=False,
    )
    assert result.returncode == 0, result.stderr.decode()


if __name__ == "__main__":
    with TemporaryDirectory(prefix="dbus-event-log-smoke-") as temporary_directory:
        asyncio.run(smoke_monitor(Path(temporary_directory) / "events.db"))
        smoke_cli_stop(Path(temporary_directory))
